# Generated by Django 4.2.9 on 2024-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstag',
            options={},
        ),
    ]
